name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: install musl lib
      run: sudo apt install musl-tools -y

    - name: add_target
      run: rustup target add x86_64-unknown-linux-musl

    - uses: actions/checkout@v6

    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl --release

    - name: Archive Bin
      uses: actions/upload-artifact@v5
      with:
        name: ddns_rust-linux-x86_64
        path: target/x86_64-unknown-linux-musl/release/ddns_rust

    - name: Build Docker Image
      run: docker build -f Dockerfile.linux -t quay.io/dlysy/cloudflareddns:linux .

    - name: quay.io login
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_IO_USERNAME }}
        password: ${{ secrets.QUAY_IO_PASSWORD }}

    - name: Push to quay.io
      run: docker push quay.io/dlysy/cloudflareddns:linux

    - name: Build Skylake
      env: 
        RUSTFLAGS: -C target-cpu=skylake
      run: cargo build --target x86_64-unknown-linux-musl --release
    
    - name: Archive Bin (Skylake)
      uses: actions/upload-artifact@v5
      with:
        name: ddns_rust-linux-x86_64-skylake
        path: target/x86_64-unknown-linux-musl/release/ddns_rust



  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: cargo build --release

      - name: Archive production artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ddns_rust-windows-x86_64
          path: target/release/ddns_rust.exe

      - name: Build Docker Image
        run: docker build -f Dockerfile.windows -t quay.io/dlysy/cloudflareddns:windows .

      - name: quay.io login
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}

      - name: Push to quay.io
        run: docker push quay.io/dlysy/cloudflareddns:windows